### ZipCode Metrics List

# This code is generating a comprehensive list of all zipcodes that contain data for a given industry level.
# We are calculating the number of unique idustries, and total numbers for employees, establishments, and payroll
# The industry level is modifiable

# We achieve this using Pandas dataframes manipulation

import os
import json, requests, csv
import pandas as pd
import argparse
import sys
from datetime import datetime

def get_directory_size(path, exclude_dirs=None):
    """Calculate total size of all files in a directory, optionally excluding subdirectories"""
    total_size = 0
    if exclude_dirs is None:
        exclude_dirs = []

    if not os.path.exists(path):
        return 0

    for dirpath, dirnames, filenames in os.walk(path):
        # Remove excluded directories from the walk
        dirnames[:] = [d for d in dirnames if d not in exclude_dirs]

        for filename in filenames:
            filepath = os.path.join(dirpath, filename)
            if os.path.exists(filepath):
                total_size += os.path.getsize(filepath)

    return total_size

def format_size(bytes_size):
    """Format bytes into human-readable format"""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if bytes_size < 1024.0:
            return f"{bytes_size:.2f} {unit}"
        bytes_size /= 1024.0
    return f"{bytes_size:.2f} TB"

# Command-line argument parsing
parser = argparse.ArgumentParser(description='Generate aggregated zipcode metrics from Census ZBP data')
parser.add_argument('year', nargs='?', default='2018', help='Census data year (default: 2018)')
parser.add_argument('--ind-level', type=str, default='6', help='Industry level (2-6, default: 6)')
parser.add_argument('--output-path', type=str, default='us/zipcodes', help='Output directory (default: us/zipcodes)')
args = parser.parse_args()

ind_level = args.ind_level
year = args.year

# Track start time
start_time = datetime.now()
start_time_str = start_time.strftime('%Y-%m-%d %H:%M:%S')

# Create output directory if it doesn't exist
if not os.path.exists(args.output_path):
    os.makedirs(args.output_path)
    print(f"Created output directory: {args.output_path}")

print(f"Sending to: {os.path.abspath(args.output_path)}")
print(f"Started: {start_time_str}")

url = f"https://api.census.gov/data/{year}/zbp?get=ZIPCODE,NAICS2017,ESTAB,EMPSZES,PAYANN&for=zipcode:*&INDLEVEL={ind_level}"

# Simple way to get all Data
orig = pd.read_json(url)
new_header = orig.iloc[0]
orig = orig[1:]
orig.columns = new_header

# Converting to Integer Values
# cannot convert to int '44-45' -> need to determine best course of action
# duplicate row with 44 and 45 line?
int_df1 = orig.astype({'NAICS2017':'str', 'ESTAB' : 'int', 'EMPSZES' : 'int', 'PAYANN' : 'int', 'ZIPCODE' : 'str'})
int_df = int_df1.rename({'ZIPCODE' : 'Zip', 'NAICS2017': 'Industries', 'ESTAB': 'Establishments', 'EMPSZES' : 'Employees', 'PAYANN' : 'Payroll'}, axis=1)
print(int_df.columns)

# Grouping (Count Unique & Sum)
gr1 = int_df[['Zip','Industries']].groupby(['Zip']).nunique()
gr2 = int_df[['Zip','Establishments', 'Employees', 'Payroll']].groupby(['Zip']).sum()

# Merging Grouped Dataframes
combined = gr1.merge(gr2, left_on='Zip', right_on='Zip')
#final_df = combined.rename({'NAICS2017': 'Industries', 'ESTAB': 'Establishments', 'EMPSZES' : 'Employees', 'PAYANN' : 'Payroll'}, axis=1)
final_df = combined


# Exporting to CSV
output_filename = f'{args.output_path}/zipcodes-naics{ind_level}-{year}.csv'
final_df.to_csv(output_filename)
print(f"Data exported to: {output_filename}")
print(final_df)

# Generate results.md
num_rows = len(final_df)
end_time = datetime.now()
end_time_str = end_time.strftime('%Y-%m-%d %H:%M:%S')
duration = end_time - start_time
duration_str = str(duration).split('.')[0]  # Remove microseconds

# Calculate directory size excluding 'naics' subfolder
total_size_bytes = get_directory_size(args.output_path, exclude_dirs=['naics'])
total_size_formatted = format_size(total_size_bytes)

script_location = os.path.abspath(__file__)
results_file = f'{args.output_path}/results.md'

results_content = f"""# Results - Zipcodes Aggregated Metrics

**Last successful completion:** {end_time_str}

## Execution Timeline

- **Start time:** {start_time_str}
- **End time:** {end_time_str}
- **Total run time:** {duration_str}

## Output Details

- **Output file:** `{os.path.basename(output_filename)}`
- **Number of rows:** {num_rows:,}
- **Industry level:** {ind_level}
- **Census year:** {year}
- **Total output size:** {total_size_formatted} (Excluding naics subfolder)

## Generation Details

- **Generated by:** `{os.path.basename(script_location)}`
- **Script location:** `{script_location}`
- **Command:** `python zipcodes.py {year} --ind-level {ind_level} --output-path {args.output_path}`

## Data Summary

The output contains aggregated metrics for {num_rows:,} zipcodes with the following columns:
- Zip (zipcode)
- Industries (unique count)
- Establishments (total)
- Employees (total)
- Payroll (total)
"""

with open(results_file, 'w') as f:
    f.write(results_content)

print(f"Results saved to: {results_file}")
print(f"Completed: {end_time_str}")
print(f"Total run time: {duration_str}")


# Testing with Small Subset
# df = pd.read_csv("test_data.csv")
# df2 = df.drop('0', inplace=False, axis=1)

# grouped1 = df2[['ZIPCODE','NAICS2017']].groupby(['ZIPCODE']).nunique()
# grouped2 = df2[['ZIPCODE','ESTAB', 'EMPSZES', 'PAYANN']].groupby(['ZIPCODE']).sum()

# final = grouped1.merge(grouped2, left_on='ZIPCODE', right_on='ZIPCODE')
# final2 = final.rename({'NAICS2017': 'Num Industries', 'ESTAB': 'Total Establishments', 'EMPSZES' : 'Total Employees', 'PAYANN' : 'Total Payroll'}, axis=1)

